version: '3.8'
services:
  main:
    container_name: ${APP_CONTAINER_NAME}
    build: .
    env_file: .env
    volumes:
      - .:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
      - ./dist:/usr/src/app/dist
    depends_on:
      - db
    links:
      - db
      - phpmyadmin
      - auth
    command: npm run start:dev
    ports:
      - ${APP_PORT}:3000

  auth:
    container_name: ${AUTH_CONTAINER_NAME}
    command: node src/server.js
    build:
      context: .
      dockerfile: ./auth-service/Dockerfile
    ports:
      - ${AUTH_PORT}:3000
    volumes:
      - ./auth-service:/app/
    environment:
      JWT_SECRET: ${JWT_SECRET}

  db:
    image: library/mysql:${MYSQL_VERSION}
    container_name: ${DATABASE_CONTAINER_NAME}
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - TERM=meh
    volumes:
      - ${DATABASE_VOLUME_MOUNT}:/var/lib/mysql

  phpmyadmin:
    image: library/phpmyadmin:latest
    container_name: ${PHPMYADMIN_CONTAINER_NAME}
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - PMA_HOST=${DATABASE_CONTAINER_NAME}
    depends_on:
      - db
    ports:
      - ${PHPMYADMIN_PORT}:80
